### ISSUE TITLE
FCFB-69 Administrators can delete embeds from the refbot

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#114]
Not sure if this is an issue or just something to be aware of. As a conference commissioner, I was able to delete the embed posted by the ref bot in the Wisconsin vs UNC scrimmage. 

[Start here for context](https://discord.com/channels/862571689342533663/1315805584905342987/1315819931769639014)

This is purely a cosmetic thing and probably isn't something that the bot can control. But I'm guessing most administrators in the server could delete an embed of a play result. This would make it harder for a player to check the previous number, result, difference, etc.

**Comment by akick31** [comment]
Unfortunately this seems to be a discord thing and can't be locked down
