### ISSUE TITLE
FCFB-16 Include clock status in all embeds

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#21]
More a suggestion but only some embeds are including the clock status

[Play result](https://discord.com/channels/862571689342533663/1299078641313120307/1299108085142523904) this does have the clock status

[Next offensive play request](https://discord.com/channels/862571689342533663/1299078641313120307/1299108174397313106) this does not

**Comment by akick31** [comment]
Updated writeup in DB to include clock status
