### ISSUE TITLE
FCFB-18 Defensive number with symbol in between gives -1

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#24]
For example, Wisconsin submitted 8+01 and the bot used -1 for the defensive number. Looks like maybe an issue if the number has a symbol in between.

**Comment by locopabs** [comment]
This is also the case with letters. I submitted 7y54 and got -1

**Comment by locopabs** [comment]
The desired result is probably what it does for [the offense](https://discord.com/channels/862571689342533663/1299078641313120307/1299116455316553728)

**Comment by akick31** [comment]
Fixed with FCFB-10
