### ISSUE TITLE
FCFB-22 No result at the end of the game

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#29]
[Here](https://discord.com/channels/862571689342533663/1299078641313120307/1299398413288341624) is the last play of the Montana State v Wisconsin scrimmage. The last play call was used but it looks like the bot ended the game before posting a result. Not knowing the steps the bot takes with each play, it looks like the posting was happening after the result was determined and acted on. 

Order of operations may need to be:
Take the number from the offense
Determine the result 
Post the result
End the game

**Comment by akick31** [comment]
Fixed in FCFB-14
