### ISSUE TITLE
FCFB-28 Time of possession

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#39]
Looking at [game 255](http://51.81.32.234:1212/arceus/game_stats?gameId=255)

The time of possession adds up to 28 minutes and 13 seconds. Not sure when in the game this stopped lining up but this should probably by 28 minutes exactly, even when a game goes into overtime.

**Comment by akick31** [comment]
I believe this is because when it adjusts the clock for end of quarter, it doesn't adjust the actual runoff time/play time to account for running over when calculating the stats

(Just putting this here for my reference later)
