### ISSUE TITLE
FCFB-29 Response speed not working with the json

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#40]
http://51.81.32.234:1212/arceus/play?playId=227

When pulling in the json with R, the last two items in the list are just null and don't easily go into a data frame

They are offensive_response_speed and defensive_response_speed. This error is because they are null/have no value. You probably have a plan for this going forward but I expect to possibly cause an issue with other JSONs as well (game stats, etc)

**Comment by akick31** [comment]
The next update will have response speeds as well as average response time for each user
