### ISSUE TITLE
FCFB-34 Relative/Dynamic timestamp for the play clock and deadline (Request/Idea)

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#46]
[Discord reference](https://discord.com/developers/docs/reference#message-formatting-formats)

That way if we have players in different time zones it will show up for the player in their time zone. Could also have both the time it runs out and the time remaining.

**Comment by akick31** [comment]
I'm not entirely sure this is possible, as the time is generated bot side and there's no Discord API to do so. I'm going to include "CST", since I believe that's what the bot time zone is using
