### ISSUE TITLE
FCFB-35 Pass Completions possibly incorrect

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#47]
Looking at passing plays in [scrimmage between Dekam and loco_pabs](https://discord.com/channels/862571689342533663/1299078641313120307) the pass completions stat may be off

Filtering on play call of pass with home team in possession, there were 49 such plays and 10 of them are incomplete. So there are at most 39 completions. Add in the couple of turnovers that takes it down to 37 completions. The stat site had 46. 

Summary: stat site/json had 46 completions on 49 pass plays for the home team, I count 37 pulling each play.

Not super important currently but probably something to be aware of.

**Comment by akick31** [comment]
Similar to FCFB-38, I think I fixed this in the backend. Leaving open just in case

**Comment by akick31** [comment]
Marking as complete, let me know if it pops up again
