### ISSUE TITLE
FCFB-38 All yards are rushing yards

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#48]
In game 255, Dekam and loco_pabs called both run and pass plays but all of the yards are attributed to rushing yards in the [stats json](http://51.81.32.234:1212/arceus/game_stats?gameId=255)

**Comment by akick31** [comment]
I think I fixed this in the backend, leaving this open just in case it wasn't

**Comment by akick31** [comment]
Marking this as complete, let me know if it pops up again
