### ISSUE TITLE
FCFB-48 Kneel should burn 40 seconds if clock is not stopped

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#66]
Kneel should burn 40 seconds off of the running clock

![image](https://github.com/user-attachments/assets/84054d3e-b030-467d-9e48-0c350da171e9)

**Comment by akick31** [comment]
Fixed in backend

**Comment by locopabs** [comment]
In Wisconsin UNC scrimmage, kneel only burned 30 seconds. Clock was running.

[Play prompt, 2:01 left](https://discord.com/channels/862571689342533663/1315805584905342987/1316970111399104595)
[Play result, 1:31 left](https://discord.com/channels/862571689342533663/1315805584905342987/1316970272510967938)
