### ISSUE TITLE
issue kicking field goal

### ISSUE THREAD

**Issue by hannahg3232** [akick31/FCFB-Zebstrika#69]
attempted to kick a 60 field goal (from opponent's 44) on 4th and 17, bot responded "There was an issue submitting the offensive number", tried again and got the same response.
attempted to punt after the second fg attempt, and the punt went through.

message link: https://discord.com/channels/862571689342533663/1304608912598630400/1304647969320075285
message id: 1304647969320075285

**Comment by akick31** [comment]
Fixed in the db
