### ISSUE TITLE
FCFB-52: game_stats endpoint down?

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#75]
Looks like the game_stats endpoints are currently down

http://51.81.32.234:1212/arceus/game_stats?gameId=255 for example

http://51.81.32.234:1212/arceus/play/all?gameId=255 (play log) works

**Comment by akick31** [comment]
It just needs the "&team=", so like: http://51.81.32.234:1212/arceus/game_stats?gameId=303&team=Maryland
