### ISSUE TITLE
FCFB-53 Weird kickoff number for defense again

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#76]
Game id: 303
Sacred Heart vs Maryland
https://discord.com/channels/862571689342533663/1305610934647132282/1305610934647132282

Maryland tried an onside kick which failed. The both then used 538 for their first defensive number and had the same issue earlier scrimmages were having

Note post in the thread
https://discord.com/channels/862571689342533663/1305610934647132282/1305615617084100658

**Comment by akick31** [comment]
I want to see if this still happens or if it was fixed by other changes

**Comment by akick31** [comment]
Going to close this since I haven't seen it pop up again, if it does we can reopen the ticket
