### ISSUE TITLE
FCFB-54 Title is posting Home vs Away

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#77]
Is this expected? Normal format for american football is Away vs Home, right? 

Not sure if it matters, this can be closed if it doesn't

**Comment by akick31** [comment]
I think when this is "home vs away" it's proper, but if it was the opposite it'd be "away @ home"?

**Comment by locopabs** [comment]
It probably doesn't matter. This might be something to check with the community about

**Comment by akick31** [comment]
Doing "away @ home", will be changed in future push
