### ISSUE TITLE
FCFB-55 No Gain Pass writeup error

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#78]
[Message link](https://discord.com/channels/862571689342533663/1305626620270219466/1305629756473217105)

{"timestamp":"2024-11-11T20:26:21.936+00:00","status":500,"error":"Internal Server Error","path":"/arceus/game_writeup/NO_GAIN/PASS"}

**Comment by akick31** [comment]
I think I fixed this one
