### ISSUE TITLE
FCFB-57: Defensive number encryption is the same each time for the same number

### ISSUE THREAD

**Issue by locopabs** [akick31/FCFB-Zebstrika#80]
[Game JSON](http://51.81.32.234:1212/arceus/play/all?gameId=310)

I submitted the same defensive number two times in a row and the temporary encryption for the defensive number was the same string both times. 

I used 841 and the string was AnlKuzTvL4qevIbahVx51g==

A player could scrape the encryptions and use this to determine numbers

**Comment by akick31** [comment]
Changed the encryption method to be better at this

**Comment by locopabs** [comment]
This is much better. I submitted the same defensive number twice after rocco did as well and got 3 very different strings. Awesome job
